### ISSUE TITLE
Get uniform response while selecting timeline modules

### ISSUE THREAD

**Issue by jamsrahimi** [HackYourFuture/hyfer#140]
The 5th click on modules in timeline will show "This module has no github repository" or sometimes the first clicks. Should be thoroughly studied.

**Comment by remarcmij** [comment]
We will get rid of the README's (except for the curriculum). Let's review again when the ModuleInfoStore has been replaced by a Mobx version (@arasmr working on this).

**Comment by remarcmij** [comment]
Fixed
