### ISSUE TITLE
Down below at front page

### ISSUE THREAD

**Issue by jamsrahimi** [HackYourFuture/hyfer#142]
Should be changed: About hyfer Hyfer is a learning platform of Hack Your Future, a code school (foundation) teaching computer programming to refugees. The website was developed as a project in Hack Your Future curriculum. Developed by Hasan Shahoud, Jack Sacali and Malek Kanaan under supervision of HYF teachers Jim Cramer,Michael Trouw,Pablo Celentano and Unmesh Joshi. Enhanced by Alumnus of Class11 .

**Comment by remarcmij** [comment]
Implemented an About page to replace the footer.
