### ISSUE TITLE
Date Picker of 'Add a new module'  is not working.

### ISSUE THREAD

**Issue by arasmr** [HackYourFuture/hyfer#151]
When you click to Add a new module button which is on the Timeline page, after you filled all information, you are not able to choose a valid date in the date picker. Date picker gets the 'min' and 'max' available time of the chosen modules but you still get error says 'Please provide a valid starting date for the module to be added'.

**Comment by remarcmij** [comment]
Implemented a new dialog with a Sunday picker/
