### ISSUE TITLE
Red highlighted current page not working

### ISSUE THREAD

**Issue by jamsrahimi** [HackYourFuture/hyfer#156]
Red underlined highlighted page (Timeline, Module...) that shows the current page, doesn't get rendered by react but only if the page is manually refreshed!

**Comment by remarcmij** [comment]
This is caused making the `Header` component a Mobx store observer. The fix is to include a `@withRouter` decorator to the component. Will be fixed in a next PR.

**Comment by remarcmij** [comment]
Fixed in PR #162
