### ISSUE TITLE
Use either yarn.lock or package-lock.json only

### ISSUE THREAD

**Issue by GeorgeSapkin** [HackYourFuture/hyfer#26]
`yarn.lock` and `package-lock.json` serve the same purpose but are used but different tools. Having them both is redundant and defeats the purpose of a lock file since different people will have different dependency versions which might lead to inconsistent results.

Consider using `yarn` instead of `npm` and getting rid of `package-lock.json`.

More about [`yarn.lock`](https://yarnpkg.com/lang/en/docs/yarn-lock/).

**Comment by remarcmij** [comment]
We will standardise on `yarn` throughout the project.
