### ISSUE TITLE
Separate devDependencies from dependencies

### ISSUE THREAD

**Issue by GeorgeSapkin** [HackYourFuture/hyfer#27]
Right now everything is in dependencies even though a lot of them (e.g. eslint) are definitely not needed for the project to run.

**Comment by mkruijt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issues](https://trello.com/c/K2hr2oH9/3-issues)

**Comment by remarcmij** [comment]
Done. Actually we have also split up the project into frontend and backend, each with its own `package.json`.
