### ISSUE TITLE
Add explicit Eslint config and stick with a single code formatting style

### ISSUE THREAD

**Issue by GeorgeSapkin** [HackYourFuture/hyfer#28]
There is no `.eslintrc` in the project and different files have different formatting which makes it difficult to read.

* Some files have both tabs and spaces in the same file: [Attendance.js](https://github.com/HackYourFuture/hyfer/blob/master/src/components/Attendance/Attendance.js)
* Sometimes closing `;` is used and sometimes not

Pick one style, configure it and stick with it.

**Comment by remarcmij** [comment]
We are adopting the Airbnb Style Guide and corresponding ESLint configs.
