### ISSUE TITLE
todayMarker is null  --  React Issue

### ISSUE THREAD

**Issue by JawharBairakdar** [HackYourFuture/hyfer#44]
I tried to follow the code to know from where it will be `null` and as i saw you are getting it from the state and the state is null, so in thiscase offcourse it will be, I couldn't figure it out because i don't know what it suppose to do.
But if there is something will have a null value in some point it should be better to have it with a conditional checking.
![screenshot-2018-4-9 hyfer](https://user-images.githubusercontent.com/25272822/38476014-e1325bba-3bab-11e8-8b80-250f006c3026.png)

**Comment by mkruijt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue 2](https://trello.com/c/rQAGZAgg/4-issue-2)
