### ISSUE TITLE
Timeline is not working with our without the existing database 

### ISSUE THREAD

**Issue by malnajar** [HackYourFuture/hyfer#53]
i have tried to run the app today with the old database but still the timeline not working and i receive this error's  from AddNewModuleModal._this.setInitialState
and the error's are :
- - [ ] min.format is not a function 
The above error occurred in the <AddNewModuleModal> component:
    in AddNewModuleModal (at AddDropdownList.js:54)

- - [ ] ./src/components/timelineComp/Timeline/Timeline.js
  Line 8:  'loader' is defined but never used  no-unused-vars

- - [ ] ./src/Pages/Users/Profile.js
  Line 5:  'notify' is defined but never

**Comment by malnajar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Timeline issue's](https://trello.com/c/UGDb9Zen/7-timeline-issues)

**Comment by malnajar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Timeline issue's](https://trello.com/c/UGDb9Zen/7-timeline-issues)

**Comment by malnajar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Timeline issue's](https://trello.com/c/UGDb9Zen/7-timeline-issues)

**Comment by mkruijt** [comment]
do you mean with **or** without 🙃?

**Comment by mkruijt** [comment]
@malnajar I was referring to a minor spelling mistake in your sentence, which can cause confusion. "with our without the existing database" -> with **or** without the existing database

**Comment by malnajar** [comment]
@mkruijt thank you so much i noticed, and i hope everything is clear now
