### ISSUE TITLE
To see my own class model not all classes

### ISSUE THREAD

**Issue by yousefallaban** [HackYourFuture/hyfer#56]
“As a user, I want to see my own class model, so that I can be focus on it .”

**Comment by yousefallaban** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [To see my own class model not all classes](https://trello.com/c/kIbIaS14/12-to-see-my-own-class-model-not-all-classes)

**Comment by remarcmij** [comment]
Needs more info.

**Comment by remarcmij** [comment]
Implemented
