### ISSUE TITLE
a bug in the timeline button "go to today"

### ISSUE THREAD

**Issue by malnajar** [HackYourFuture/hyfer#57]
when you press on the button in the timeline the app will crash and you will receive this error:

TypeError: Cannot read property 'parentNode' of null
Timeline._this.handleClickTodayMarker
line: Timeline.js:85

**Comment by malnajar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [go to today button in timeline issue](https://trello.com/c/Ub6bGc7o/13-go-to-today-button-in-timeline-issue)

**Comment by JawharBairakdar** [comment]
it works fine

**Comment by remarcmij** [comment]
Fixed
