### ISSUE TITLE
#  class activity(event)

### ISSUE THREAD

**Issue by yousefallaban** [HackYourFuture/hyfer#58]
“As a user, I want to be able to see my class activity such as **Youtube** so that I can see all my class activity in one place.”

**Comment by yousefallaban** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [class activity](https://trello.com/c/SyVGok2h/14-class-activity)

**Comment by malnajar** [comment]
also if the teacher would like to add more resources or specify a day for the hangout

**Comment by remarcmij** [comment]
Implemented through Module Notes.
