### ISSUE TITLE
Not able to add new class to the api even though all requirements are met, I think

### ISSUE THREAD

**Issue by JiDarwish** [HackYourFuture/hyfer#6]
https://github.com/HackYourFuture/hyfer/blob/c4cd1102da0b005ecede041235e75f214d02ec92/src/store/TimeLineStore.js#L85

Hey guys I'm getting an an `internal server error` response once this gets executed and I've compared it to what the current hyfer page does it's quiet the same. Could any of you take look and let me know what you think it is? Thanks

**Comment by JiDarwish** [comment]
It was a very bug stupid and is now closed thanks to @remarcmij

**Comment by mkruijt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issues](https://trello.com/c/K2hr2oH9/3-issues)

**Comment by mkruijt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issues](https://trello.com/c/K2hr2oH9/3-issues)
