### ISSUE TITLE
no one can delete a class from the app :D 

### ISSUE THREAD

**Issue by malnajar** [HackYourFuture/hyfer#60]
we need to make a button that also can delete a class and in this case we need to know after deleting a class where the students will end up ... should they still can use the app or by deleting the app we should just close it so it will not show up in the timeline (in this case also we have to add in the class table status for example "open" or "closed"

**Comment by malnajar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The ability of deleting a class through the app](https://trello.com/c/JZLTXCk3/16-the-ability-of-deleting-a-class-through-the-app)

**Comment by M3kH** [comment]
We don't wanna delete a class. But probably we wanna notify that they graduate.

**Comment by remarcmij** [comment]
Classes are not deleted. We set the archive bit in the database. Archived classes do not show up in timeline.
