### ISSUE TITLE
can't assign new teacher in the module

### ISSUE THREAD

**Issue by jalalalwani** [HackYourFuture/hyfer#61]
while trying to assign teacher in one of the modules, there is no way to write or select any teacher from the database, there only teacher(1/2) and nothing can be done.

**Comment by jalalalwani** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [can't assign a teacher for a specific module.](https://trello.com/c/ELR0JCwa/17-cant-assign-a-teacher-for-a-specific-module)

**Comment by remarcmij** [comment]
Fixed
